### ISSUE TITLE
Expected string, received null

### ISSUE THREAD

**Issue by SDS-DEV6** [fajarwz/blog-nextjs-auth#1]

**Comment by fajarwz** [comment]
it looks like your problem is resolved, thanks for using my repo and reading my article. If you like it, consider giving it a star and sharing the article with your fellow developers.

I will close this issue. You can reopen or create a new issue if there are still other issues

**Comment by SDS-DEV6** [comment]
oh apologies forgot to mention it whenever i try to use this but with a different ui style the user inputs are returned as null

**Comment by fajarwz** [comment]
can you give me more info about the error, like post all of the code related and screenshots of the error here?

**Comment by SDS-DEV6** [comment]
managed to address the problem. This was the code when the issue appeared. I'll be closing this since its not much of an issue related to your work more of how I might have mishandled the divs 


 <div>
      <div className="flex items-center flex-col h-full w-full p-10 bg-white">
        <div className="flex flex-col justify-center items-center">
          <Image /src={PikuImage}/ width={197} height={159} alt="Piku-ad" />
          <div className="bg-slate-50 p-6 border rounded-2xl font-quicksand text-blackberry-300">
            <div>
              <div className="flex flex-col items-center justify-center text-base">
                <div className="text-2xl font-extrabold font-raleway">
                  Create an Account
                </div>
                <div className="flex flex-row  items-center justify-center gap-2 text-base mt-2">
                  <div className="font-inter font-normal">
                    Don't have an account?
                  </div>
                  <Link href="/signup">Sign Up</Link>
                </div>
              </div>
              <div>
                <form action={action} className="mt-4">
                  <div className="mb-4">
                    <label
                      htmlFor="email"
                      className="block text-slate-700 text-sm font-bold mb-2 mt-3"
                    >
                      Email
                    </label>
                    <input
                      className="shadow-sm appearance-none border rounded w-full py-2 px-3 text-slate-700 leading-tight focus:outline-none focus:shadow-outline"
                      id="email"
                      type="text"
                      placeholder="Enter Email"
                      required
                    />

                    <label
                      htmlFor="password"
                      className="block text-slate-700 text-sm font-bold mb-2 mt-3"
                    >
                      Password
                    </label>

                    <input
                      className="shadow-sm appearance-none border rounded w-full py-2 px-3 text-slate-700 leading-tight focus:outline-none focus:shadow-outline"
                      id="password"
                      type="password"
                      placeholder="Enter Password"
                    />
                    <div className="absolute insert-y-0 right-0 pr-3 flex items-center text-sm leading-5"></div>
                  </div>

                  <div className="flex flex-row  items-center justify-center gap-2 font-inter text-sm font-medium">
                    <div className="font-inter font-normal">
                      Forgot Password?
                    </div>
                    <a className="text-blackberry-300 hover:opacity-50 font-inter text-sm font-medium">
                      Reset
                    </a>
                  </div>

                  <LoginButton />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
